/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class admin extends javax.swing.JFrame {

    private String hakAkses;

    // Konstruktor yang menerima hak akses sebagai parameter
    public admin(String hakAkses) {
        this.hakAkses = hakAkses;
        initComponents();
        checkAccess();
    }
    
    // Metode default constructor yang memanggil konstruktor utama dengan parameter null
    public admin() {
        this(null); // or set a default value like "admin"
    }

    private void checkAccess() {
        if ("guru".equals(hakAkses)) {
            admButton.setEnabled(false); // Disable Data Admin button
            guruButton.setEnabled(false); // Disable Data Siswa button
            siswaButton.setEnabled(false); // Disable Data Guru button
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customUI1 = new necesario.CustomUI();
        admButton = new rojerusan.RSMaterialButtonRectangle();
        guruButton = new rojerusan.RSMaterialButtonRectangle();
        siswaButton = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admButton.setBackground(new java.awt.Color(51, 52, 55));
        admButton.setBorder(null);
        admButton.setText("Data Admin");
        admButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        admButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admButtonActionPerformed(evt);
            }
        });
        getContentPane().add(admButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 410, 70));

        guruButton.setBackground(new java.awt.Color(51, 52, 55));
        guruButton.setBorder(null);
        guruButton.setText("DATA GURU");
        guruButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        guruButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guruButtonActionPerformed(evt);
            }
        });
        getContentPane().add(guruButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 410, 70));

        siswaButton.setBackground(new java.awt.Color(51, 52, 55));
        siswaButton.setBorder(null);
        siswaButton.setText("DATA SISWA");
        siswaButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        siswaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siswaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(siswaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 410, 70));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle1.setBorder(null);
        rSMaterialButtonRectangle1.setForeground(new java.awt.Color(255, 0, 0));
        rSMaterialButtonRectangle1.setText("Logout");
        rSMaterialButtonRectangle1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 160, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_login/dashboardAdm.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admButtonActionPerformed
        new daMin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_admButtonActionPerformed

    private void guruButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guruButtonActionPerformed
        new daRu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guruButtonActionPerformed

    private void siswaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siswaButtonActionPerformed
        new daSis().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_siswaButtonActionPerformed

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle admButton;
    private necesario.CustomUI customUI1;
    private rojerusan.RSMaterialButtonRectangle guruButton;
    private javax.swing.JLabel jLabel1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle siswaButton;
    // End of variables declaration//GEN-END:variables
}
