/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class daSis extends javax.swing.JFrame {
    private Connection conn;

    public daSis() {
        initComponents();
        connectToDatabase(); // Koneksi ke database
        loadKelasToComboBox(); // Mengisi data kelas ke ComboBox
        refreshTable(); // Menampilkan data siswa pada tabel

        // Listener untuk mengisi form ketika baris tabel diklik
        tableSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSiswaMouseClicked(evt);
            }
        });
    }
    
    // Mengisi ComboBox dengan data kelas dari database
    private void loadKelasToComboBox() {
        try {
            String query = "SELECT id_kelas, nama_kelas FROM kelas";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            inputKelas.removeAllItems(); // Hapus semua item yang ada di ComboBox

            while (rs.next()) {
                String kelas = rs.getString("nama_kelas");
                String display = kelas;
                inputKelas.addItem(display);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    
    
     private void connectToDatabase() {
        try {
            String url = "jdbc:mysql://localhost:3306/db_presencepro";
            String user = "root";
            String password = "";

            conn = DriverManager.getConnection(url, user, password);
            System.out.println("Koneksi ke database berhasil!");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Koneksi ke database gagal!");
        }
    }

    
     // Mengisi form ketika baris tabel diklik
    private void tableSiswaMouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = tableSiswa.getSelectedRow();
        if (selectedRow != -1) {
            String nisn = tableSiswa.getValueAt(selectedRow, 0).toString();
            String nis = tableSiswa.getValueAt(selectedRow, 1).toString();
            String nama = tableSiswa.getValueAt(selectedRow, 2).toString();
            String kelas = tableSiswa.getValueAt(selectedRow, 3).toString();

            inputNisn.setText(nisn);
            inputNis.setText(nis);
            inputNama.setText(nama);
            inputKelas.setSelectedItem(kelas);
        }
    }
    
     // Mengambil data siswa dan mengisi tabel
   private void refreshTable() {
    try {
        String query = "SELECT s.nisn, s.nis, s.nama_siswa, CONCAT(k.id_kelas, ' - ', k.nama_kelas) AS kelas_info " +
                       "FROM siswa s JOIN kelas k ON s.id_kelas = k.id_kelas";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);

        DefaultTableModel model = (DefaultTableModel) tableSiswa.getModel();
        model.setRowCount(0); // Hapus semua baris yang ada

        while (rs.next()) {
            String nisn = rs.getString("nisn");
            String nis = rs.getString("nis");
            String nama = rs.getString("nama_siswa");
            String kelas_info = rs.getString("kelas_info");

            model.addRow(new Object[]{nisn, nis, nama, kelas_info});
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();
        inputNisn = new javax.swing.JTextField();
        inputKelas = new javax.swing.JComboBox<>();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        tambahButton = new rojerusan.RSMaterialButtonRectangle();
        editButton = new rojerusan.RSMaterialButtonRectangle();
        deletButton = new rojerusan.RSMaterialButtonRectangle();
        batalButton = new rojerusan.RSMaterialButtonRectangle();
        kembaliButton = new rojerusan.RSMaterialButtonRectangle();
        inputNis = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputNama.setBackground(new java.awt.Color(51, 52, 55));
        inputNama.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        inputNama.setForeground(new java.awt.Color(255, 255, 255));
        inputNama.setBorder(null);
        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });
        getContentPane().add(inputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 402, 280, 40));

        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "nisn", "nis", "nama", "kelas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableSiswa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 710, 550));

        inputNisn.setBackground(new java.awt.Color(51, 52, 55));
        inputNisn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        inputNisn.setForeground(new java.awt.Color(255, 255, 255));
        inputNisn.setBorder(null);
        inputNisn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNisnActionPerformed(evt);
            }
        });
        getContentPane().add(inputNisn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 270, 50));

        inputKelas.setBackground(new java.awt.Color(51, 52, 55));
        inputKelas.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        inputKelas.setForeground(new java.awt.Color(255, 255, 255));
        inputKelas.setBorder(null);
        inputKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKelasActionPerformed(evt);
            }
        });
        getContentPane().add(inputKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 290, 70));

        rSMaterialButtonRectangle1.setText("rSMaterialButtonRectangle1");
        getContentPane().add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        tambahButton.setBackground(new java.awt.Color(0, 255, 0));
        tambahButton.setBorder(null);
        tambahButton.setText("tambah");
        tambahButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });
        getContentPane().add(tambahButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 100, 50));

        editButton.setBorder(null);
        editButton.setText("edit");
        editButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 100, 50));

        deletButton.setBackground(new java.awt.Color(255, 0, 0));
        deletButton.setBorder(null);
        deletButton.setText("delete");
        deletButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        deletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deletButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 100, 50));

        batalButton.setBackground(new java.awt.Color(1, 94, 1));
        batalButton.setBorder(null);
        batalButton.setText("batal");
        batalButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });
        getContentPane().add(batalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 140, 60));

        kembaliButton.setBackground(new java.awt.Color(0, 8, 250));
        kembaliButton.setBorder(null);
        kembaliButton.setText("kembali");
        kembaliButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });
        getContentPane().add(kembaliButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 640, 150, 60));

        inputNis.setBackground(new java.awt.Color(51, 52, 55));
        inputNis.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        inputNis.setForeground(new java.awt.Color(255, 255, 255));
        inputNis.setBorder(null);
        getContentPane().add(inputNis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 280, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_login/DataSiswa.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNisnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNisnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNisnActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        String nisn = inputNisn.getText();
    String nis = inputNis.getText();
    String nama = inputNama.getText();
    String kelas = (String) inputKelas.getSelectedItem();
    
    // Query to get the id_kelas from the kelas table based on nama_kelas
    int kelasId = getKelasId(kelas);

    if (kelasId == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Kelas tidak ditemukan.");
        return; // Exit the method if the kelasId is invalid
    }

    try {
        String query = "INSERT INTO siswa (nisn, nis, nama_siswa, id_kelas, username) VALUES (?, ?, ?, ?, 'Tes', '123')";
        PreparedStatement pstmt = conn.prepareStatement(query);
        pstmt.setString(1, nisn);
        pstmt.setString(2, nis);
        pstmt.setString(3, nama);
        pstmt.setInt(4, kelasId);
        pstmt.executeUpdate();

        inputNisn.setText("");
        inputNis.setText("");
        inputNama.setText("");
        inputKelas.setSelectedItem("");
        refreshTable(); // Refresh the table
    } catch (Exception e) {
        e.printStackTrace();
    }
}                                            

private int getKelasId(String namaKelas) {
    try {
        String query = "SELECT id_kelas FROM kelas WHERE nama_kelas = ?";
        PreparedStatement pstmt = conn.prepareStatement(query);
        pstmt.setString(1, namaKelas);
        ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            return rs.getInt("id_kelas");
        } else {
            return -1; // Return -1 if kelas is not found
        }
    } catch (SQLException e) {
        e.printStackTrace();
        return -1; // Return -1 in case of an error
    }

    }//GEN-LAST:event_tambahButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
         try {
            String nisn = inputNisn.getText();
            String nis = inputNis.getText();
            String nama = inputNama.getText();
            String kelas = inputKelas.getSelectedItem().toString();
            int kelasId = Integer.parseInt(kelas.split(" - ")[0]);
            

            if (nisn.isEmpty() || nis.isEmpty() || nama.isEmpty()|| kelas.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "All fields must be filled out.");
                return; // Prevent the operation if validation fails
            }
                String query = "UPDATE siswa SET nis = ?, nama = ?, kelas_id = ? WHERE nisn = ?";
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setString(1, nis);
            pstmt.setString(2, nama);
            pstmt.setInt(3, kelasId);
            pstmt.setString(4, nisn);
            pstmt.executeUpdate();
            refreshTable();
                
            } catch (Exception e) {
                e.printStackTrace();
            }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletButtonActionPerformed
        try {
          String nisn = inputNisn.getText();
          String query = "DELETE FROM  siswa WHERE nisn = ?";
          
          PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setString(1, nisn);
            
            pstmt.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            e.printStackTrace();
       }
    }//GEN-LAST:event_deletButtonActionPerformed

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalButtonActionPerformed
       inputNisn.setText("");
        inputNama.setText("");
        inputNis.setText("");
        inputKelas.setSelectedItem("");
    }//GEN-LAST:event_batalButtonActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        new admin().setVisible(true); // Open the admin window
        this.dispose(); // Close the current window
    }//GEN-LAST:event_kembaliButtonActionPerformed

    private void inputKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKelasActionPerformed

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daSis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daSis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daSis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daSis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daSis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle batalButton;
    private rojerusan.RSMaterialButtonRectangle deletButton;
    private rojerusan.RSMaterialButtonRectangle editButton;
    private javax.swing.JComboBox<String> inputKelas;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputNis;
    private javax.swing.JTextField inputNisn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSMaterialButtonRectangle kembaliButton;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private javax.swing.JTable tableSiswa;
    private rojerusan.RSMaterialButtonRectangle tambahButton;
    // End of variables declaration//GEN-END:variables
}
