/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BAYU CANDRA Y
 */
public class guru extends javax.swing.JFrame {

    /**
     * Creates new form guru
     */
    public guru() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRiwayatKehadiran = new rojerusan.RSMaterialButtonRectangle();
        buttonKehadiran = new rojerusan.RSMaterialButtonRectangle();
        buttonPelajaran = new rojerusan.RSMaterialButtonRectangle();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonRiwayatKehadiran.setBackground(new java.awt.Color(51, 52, 55));
        buttonRiwayatKehadiran.setText("RIWAYAT KEHADIRAN");
        buttonRiwayatKehadiran.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        buttonRiwayatKehadiran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRiwayatKehadiranActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRiwayatKehadiran, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 410, 70));

        buttonKehadiran.setBackground(new java.awt.Color(51, 52, 55));
        buttonKehadiran.setText("INPUT KEHADIRAN");
        buttonKehadiran.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        buttonKehadiran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKehadiranActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKehadiran, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 410, 70));

        buttonPelajaran.setBackground(new java.awt.Color(51, 52, 55));
        buttonPelajaran.setText("JADWAL PELAJARAN");
        buttonPelajaran.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        buttonPelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPelajaranActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPelajaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 410, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_login/DashboardGuru.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKehadiranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKehadiranActionPerformed
        new absen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonKehadiranActionPerformed

    private void buttonPelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPelajaranActionPerformed
        new jadwalGuru().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonPelajaranActionPerformed

    private void buttonRiwayatKehadiranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRiwayatKehadiranActionPerformed
//        new riwayatHadir().setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_buttonRiwayatKehadiranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle buttonKehadiran;
    private rojerusan.RSMaterialButtonRectangle buttonPelajaran;
    private rojerusan.RSMaterialButtonRectangle buttonRiwayatKehadiran;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
