/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.*;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
/**
 *
 * @author user
 */
public class login extends javax.swing.JFrame {
    String user = "root";
    String pwd = "";
    String url = "jdbc:mysql://localhost:3306/db_presencepro";
    
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setLocationRelativeTo(this);
    }
    
    void Login() {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    try {
        con = DriverManager.getConnection(url, user, pwd);
        
        // Mengambil input dari field usr dan pas
        String username = usr.getText();
        String password = pas.getText();
        
        // Query untuk mengecek username dan password di tabel guru, admin, atau siswa
        String sqlGuru = "SELECT * FROM guru WHERE username = ? AND password = ?";
        String sqlAdmin = "SELECT * FROM admin WHERE username = ? AND password = ?";
        String sqlSiswa = "SELECT * FROM siswa WHERE username = ? AND password = ?";

        // Periksa tabel guru terlebih dahulu
        pst = (PreparedStatement) con.prepareStatement(sqlGuru);
        pst.setString(1, username);
        pst.setString(2, password);
        rs = pst.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(null, "Welcome Guru");
            new guru().setVisible(true); // Form Guru
            this.dispose(); // Menutup form login
            return;
        }

        // Periksa tabel admin
        pst = (PreparedStatement) con.prepareStatement(sqlAdmin);
        pst.setString(1, username);
        pst.setString(2, password);
        rs = pst.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(null, "Welcome Admin");
            new admin().setVisible(true); // Form Admin
            this.dispose();
            return;
        }

        // Periksa tabel siswa
        pst = (PreparedStatement) con.prepareStatement(sqlSiswa);
        pst.setString(1, username);
        pst.setString(2, password);
        rs = pst.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(null, "Welcome Siswa");
            new daSis().setVisible(true); // Form Siswa
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Username atau Password salah");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Koneksi Gagal: " + e.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            if (con != null) con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error saat menutup koneksi: " + e.getMessage());
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usr = new javax.swing.JTextField();
        pas = new javax.swing.JTextField();
        pas1 = new javax.swing.JTextField();
        pas2 = new javax.swing.JTextField();
        login = new rojerusan.RSMaterialButtonRectangle();
        kembaliButton = new rojerusan.RSMaterialButtonRectangle();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_login/Login (1).png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usr.setBackground(new java.awt.Color(28, 29, 33));
        usr.setForeground(new java.awt.Color(255, 255, 255));
        usr.setBorder(null);
        usr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrActionPerformed(evt);
            }
        });
        getContentPane().add(usr, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 300, 20));

        pas.setBackground(new java.awt.Color(28, 29, 33));
        pas.setForeground(new java.awt.Color(255, 255, 255));
        pas.setBorder(null);
        pas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasActionPerformed(evt);
            }
        });
        getContentPane().add(pas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 280, 20));

        pas1.setBackground(new java.awt.Color(28, 29, 33));
        pas1.setBorder(null);
        pas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pas1ActionPerformed(evt);
            }
        });
        getContentPane().add(pas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 150, 20));

        pas2.setBackground(new java.awt.Color(28, 29, 33));
        pas2.setBorder(null);
        pas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pas2ActionPerformed(evt);
            }
        });
        getContentPane().add(pas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 150, 20));

        login.setBackground(new java.awt.Color(156, 111, 228));
        login.setBorder(null);
        login.setText("login");
        login.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 310, 60));

        kembaliButton.setBackground(new java.awt.Color(156, 111, 228));
        kembaliButton.setBorder(null);
        kembaliButton.setText("kembali");
        kembaliButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });
        getContentPane().add(kembaliButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 310, 60));

        jLabel2.setBackground(new java.awt.Color(51, 52, 55));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_login/logPre.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrActionPerformed

    private void pasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasActionPerformed

    private void pas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pas1ActionPerformed

    private void pas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pas2ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        Login();
    }//GEN-LAST:event_loginActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
       new main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private rojerusan.RSMaterialButtonRectangle kembaliButton;
    private rojerusan.RSMaterialButtonRectangle login;
    private javax.swing.JTextField pas;
    private javax.swing.JTextField pas1;
    private javax.swing.JTextField pas2;
    private javax.swing.JTextField usr;
    // End of variables declaration//GEN-END:variables
}
